---
title: Your Awesome Website
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-agency
url: ''
baseurl: ''
email: your-email@example.com
description: Site description
author: Your Name
locale: en-US
analytics:
  google: 
markdown: kramdown
